#! /bin/sh
#stribog top: autoreconf and some other tricks to regenerate build system
#Copyright (C) 2008\
# Ineiev<ineiev@users.sourceforge.net>, super V 93
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.
echo regen_configure: regenerating hw/Makefile.am
cd hw;m4 -I . < Makefile.am.m4 > Makefile.am;cd ..
autoreconf -v
echo regen_configure: adding sw/target/configure.pre to sw/target/configure
cd sw/target; ./regen_configure;cd ../..
echo regen_configure: cleaning unfavoured files
rm -fr autom4te.cache config.h.in~ sw/host/autom4te.cache
