#! /bin/bash
#process stribog data; the data are to have been preprocessed with expon;
sort -nk2 $1 |grep -v ": *-1"|uniq >data
grep adc data|cut -d':' -f2 >adc.dat
cat calib.dat data |bin/exvel $2 >data.proc
grep "^acc_pos:" <data.proc |cut -d':' -f2 >acc_pos
grep "^xvel:" <data.proc |cut -d':' -f2 >xvel
grep "^v_angle:" <data.proc|cut -d':' -f2 >v_angle
grep "^extra_pos:" <data.proc|cut -d':' -f2 >extra_pos
grep "^trans_tang_error:" <data.proc|cut -d':' -f2 >tterr
grep "^gyro_trans_tang_error:" <data.proc|cut -d':' -f2 >gterr
grep "^gyro_pos:" <data.proc|cut -d':' -f2 >gyro_pos
grep "^extra_gyro_pos:" <data.proc|cut -d':' -f2 >extra_gyro_pos
grep "^extra_gps:" <data.proc|cut -d':' -f2 >extra_gps
#This program is a part of the stribog host software section
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
#Copyright (C) 2006 D.Ineiev <ineiev@yahoo.co.uk>
