#! /bin/bash
#makes files to feed elk
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#Copyright (C) 2005, 2006, 2007 D.Ineiev <ineiev@yahoo.co.uk>
target=multa
if [ $# -gt 0 ]; then target=$1; fi
echo cooking $target
cd ../../target/;make;cd ../host/elk
cp ../../target/bin/$target.bin elk.bin;cp ../../target/bin/$target.vectors vectors
