#! /bin/bash
#makes files to feed elk
#Copyright (C) 2005, 2006, 2007, 2008\
# Ineiev<ineiev@users.sourceforge.net>, super V 93
#to load the resulting files into the mainboard, run
#$./elk [serial port file] -1
# e.g. 
#$./elk /dev/ttyS0 -1
#
#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.
target=multa
if [ $# -gt 0 ]; then target=$1; fi
echo cooking $target
cd ../../target/;make;cd ../host/elk
cp ../../target/bin/$target.bin elk.bin
intlpc < ../../target/bin/$target.bin_rom > elk.bin_rom
cp ../../target/bin/$target.vectors vectors
